#https://www.practicepython.org/exercise/2014/07/05/18-cows-and-bulls.html

"""
Docstring for practicepython.org.cows_and_bulls
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit 
that the user guessed correctly in the correct place, they have a “cow”. For every digit the 
user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, 
tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, 
the game is over. Keep track of the number of guesses the user makes throughout the game and 
tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""
import random

def num_generator() -> str: 
    return str(random.randint(1000,9999))


def main():
    print("---Cows and Bulls--- \nGuess the 4-digit Number\n")
    guess_count = 0
    random_number = num_generator()
    while True:
        user_input = input("Enter a number: ")
        if len(user_input) != 4 or not user_input.isdigit():
            print("Please enter a 4-digit number.") 
            continue

        guess_count += 1
        cow_count, bull_count = cow_bull(user_input, random_number)

        if cow_count == 4:
            print(f"You win!\nYou guessed the number right in {guess_count} {'attempts' if guess_count > 1 else 'attempt'}.")
            break
        else:
            print(f"{cow_count} {'cows' if cow_count > 1 else 'cow'}, {bull_count} {'bulls' if bull_count > 1 else 'bull'}")



def cow_bull(guess, num):  #guess is user input,  num  is number to be guessed
    cow_count = sum(g == n for g, n in zip(guess, num))
    bull_count = sum(min(guess.count(d), num.count(d)) for d in set(guess)) - cow_count
    
    return cow_count, bull_count

if __name__ == "__main__":
    main()