#https://www.practicepython.org/exercise/2014/02/15/03-list-less-than-ten.html


#comment for myself / thought process
"""
Problem is:
    Take a list, say for example this one:

  a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
and write a program that prints out all the elements of the list that are less than 5.
    ----try to solve 
    so for list we can do like a for loop on that list and check every element and print it out directly
    list = [1, 2, 3, 4, 5, 6, 7] sample
    for element in list:
        if element < 5:
            print(element)
    somthing like that maybe
    or do a 
    for element in [element for element in list if element < 5]:
        print(element)
    or just straight up do a link comprehension
    [print(element) for element in list if element < 5] 
    and I think this should do it with this problem:

    ---Now for Extra challenge---
    1. Instead of printing the elements one by one, make a new list that has all the elements less than 5 from this list inm it and priuntout this new list.
    2. Write this in one line of python
    3. Ask the user for a number and return a list that contains only elements from the original list 'a' that are smaller than that number given by the user.

    Upon analyzing this extra challenge. I find the problem now actually more vague..
    It does not state how we take in a list...
    it could be a user define or a programmer-made list
    so on this challenge I would just do a 10-element list, where all the element is a random integer generated by random using the random module randint(0,20)
    listahan = [randint(0,100) for _ in range(10)]
    we can then print this is 
    print('Original List: ',listahan)  so we know what's the element on our random list before our code implementation.

    Now to solve this 3 extra challenge.
    1. So using the 'listahan' list we just have to create a new list where we add all the elements that are less than 5.
    listahan = [random original list]
    new_list = append all elements from the original list that are < 5.
            we can do a link comprehension [n for n in listahan if n < 5] or a for loop


    Second Challenge, We have already solve this above:
        →     [print(element) for element in list if element < 5] 
    
    Third Challenge, ask a user for a number then convert to int type and use it inside the list comprehension

    Implementation: 

    So I assume all these 3 extra challenge would be a different partition of a program:
    I can argue that the first and second challenge can be done in a one liner combined, but for the 3rd  one, asking for an input inside a link comprehension
    would not work out as I would like it to be: 
    so I would just now divide this challenge into 3 separate part of a program
        1. One for the first extra challenge
        2. another part for the one-liner challenge and (also the basic challenge solution), it will not really be a one-liner since we will be generating the random list but the code solution is indeed a 1-line
        3. Last part for asking a user input where I can reference it in comparing for the elements in the list
    and for each of this part we would be using a different list for each in which we would be printing out before the actual output solution for each part:
        so it would be printed out like
        List1: [1, 5, 6, 7, 8, 3, 10, 8 , 20 , 1] #sample generated
        [1,3, 1]    #Sample output after the applying the logic of the first part of the solution

        List2: [2, 5, 6, 7, 8, 3, 10, 8 , 20, 2] #sample generated
        2 3 2

        List3: [3, 5, 6, 7, 8, 3, 10, 8 , 20 , 3]
        Enter a number:       #this is for prompting user 
        #so for example if user input 8, list returned would be:
        [3, 5, 6, 7, 3, 3] 

        
"""

import sys
from random import randint

list1 = [randint(0,20) for _ in range(10)]
print("First List: ", list1)
new_list1 = []

for n in list1:
    if n < 5:
        new_list1.append(n)
print(new_list1)



list2 = [randint(0,20) for _ in range(10)]
print("\nSecond List: ", list2)
[print(e,end=' ') for e in list2 if e < 5]  #since basic challenge is just printing the elements  and not the whole printed out list or at least that's what I understood 

print('\n')
try:
    user_input = int(input("Enter a number: "))
except ValueError:
    sys.exit("Not a number.")

list3 = [randint(0,20) for _ in range(10)]
print("Third List: ", list3)
new_list3 = [n for n in list3 if n < user_input]
print(new_list3)